
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rentai-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: rentai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rentai-frontend
                port:
                  number: 8501
